a = input("Digite algo: ")
print(f"Tipo do arquivo: {type(a)}")
print(f"Tem apenas espaços? ", a.isspace())
print(f"É um número? ", a.isnumeric())
print(f"É alfabético?", a.isalpha())
print(f"É alfanúmerico? ", a.isalnum())
print(f"Está em letras maiúsculas? ", a.isupper())
print(f"Está em letras minúsculas? ", a.islower())
print(f"Está capitalizada? ", a.istitle())